### ISSUE TITLE
New release to PyPI?

### ISSUE THREAD

**Issue by msabramo** [pdbpp/fancycompleter#20]
It looks like the last PyPI release was 0.8 (Oct. 25, 2017).

**Comment by blueyed** [comment]
See https://github.com/pdbpp/pdbpp/issues/260

**Comment by blueyed** [comment]
@msabramo 
btw: why are you interested in a release?
Do you use it with something else than pdbpp?

**Comment by msabramo** [comment]
Nah I think pdbpp is the only thing that I use that uses fancycompleter. I was just going through all of the open source projects that I have an involvement with and trying to close out issues. Plus I remember the last time I tried to use pdbpp, tab completion wasn't working and I had to install a fork or something of fancycompleter to get it to work.

**Comment by blueyed** [comment]
https://pypi.org/project/fancycompleter/0.9.1/
