### ISSUE TITLE
Unable to setup fancycompleter 0.9.0 for Python 2.7 with LANG=C

### ISSUE THREAD

**Issue by imankulov** [pdbpp/fancycompleter#32]
I came across this issue when tried to set this up on my local development environment. The issue can be reproduced with a Docker python2.7

```bash
docker run --rm -i -t -e LANG=C python:2.7 pip install fancycompleter
```

```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting fancycompleter
  Downloading fancycompleter-0.9.0.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zu5MqZ/fancycompleter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zu5MqZ/fancycompleter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-zu5MqZ/fancycompleter/pip-egg-info
         cwd: /tmp/pip-install-zu5MqZ/fancycompleter/
    Complete output (20 lines):
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zu5MqZ/fancycompleter/setup.py", line 32, in <module>
        "pyreadline;platform_system=='Windows'",
      File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python2.7/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/tmp/pip-install-zu5MqZ/fancycompleter/.eggs/setupmeta-2.6.18-py2.7.egg/setupmeta/hook.py", line 23, in distutils_hook
        dist._setupmeta = SetupMeta(dist)
      File "/tmp/pip-install-zu5MqZ/fancycompleter/.eggs/setupmeta-2.6.18-py2.7.egg/setupmeta/model.py", line 626, in __init__
        self.pkg_info = PackageInfo(MetaDefs.project_dir)
      File "/tmp/pip-install-zu5MqZ/fancycompleter/.eggs/setupmeta-2.6.18-py2.7.egg/setupmeta/model.py", line 403, in __init__
        lines = load_contents(self.path)
      File "/tmp/pip-install-zu5MqZ/fancycompleter/.eggs/setupmeta-2.6.18-py2.7.egg/setupmeta/content.py", line 29, in load_contents
        for line in fh:
      File "/usr/local/lib/python2.7/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3592: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I dug a bit deeper, and I believe that the issue is that README.md, which is included in the egg package, has a non-ASCII `just work™` clause. Is there any chance you can remove this symbol and re-upload a new patch version of the package?

Thanks!

**Comment by blueyed** [comment]
Thanks for the report.  I've uploaded 0.9.1: https://pypi.org/project/fancycompleter/0.9.1/

**Comment by imankulov** [comment]
Thanks a lot for the quick turnaround 🎉  I can confirm that it works with 0.9.1

**Comment by blueyed** [comment]
:+1: 
Setting up deployment via Travis was worth it then already almost.. :)

**Comment by blueyed** [comment]
btw: what are you using it for?  pdb++ or something else?
As for py3 and in general I recommend to use pyrepl from Git's master branch also.

**Comment by imankulov** [comment]
> btw: what are you using it for? pdb++ or something else?

Yes, it's pdb++. I got used to pdb++ so much that whenever I use stock pdb, I feel like there's something broken under my fingertips.

**Comment by blueyed** [comment]
I know.. :)
Is it pdb++ from master then or the old release?
Releasing is kind of blocked by https://github.com/pdbpp/pdbpp/issues/260.
I plan to eventually make fancycompleter / pyrepl optional dependencies, since I am slowly switching to using it with ipython/ipdb by now.

**Comment by zsimic** [comment]
If you change your invocation to `LANG=C.UTF-8` this would work even with unicode in the README.

`LANG=C` seems to be interpreted by python2 as "do strict ASCII"

**Comment by zsimic** [comment]
Confirmed this works (but fails with `LANG=C`):
```
docker run --rm -i -t -e LANG=C.UTF-8 python:2.7 pip install fancycompleter==0.9.0
```

I'd love to know how to make python `io.open(some_path, "rt")` work with py2.7 even if `LANG` is not set properly. The issue seems to affect py2.7 only.

**Comment by blueyed** [comment]
@zsimic 
Thanks for your interest/help.
As for me I am OK with removing "™" from the readme, which also showed some other misplaced quotes, and I've ignored the readme being out of date probably anyway.
I would not spend much time with py27 support, especially if it can be worked around.
