### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by kynan** [pdbpp/fancycompleter#34]
This repo is strictly speaking not licensed, so no one can use it.

I requested @antocuni to add a license already 3 years ago: https://bitbucket.org/antocuni/fancycompleter/issues/5/add-license-file

A license is now a requirement for packaging.

**Comment by antocuni** [comment]
I am fine to add a LICENSE file to repo and release my work under either BSD or MIT.
I leave the final decision to the current maintainers also because there are commits which are not mine and for which I don't have any right to decide which license to apply.

**Comment by kynan** [comment]
Thank you so much for confirming, @antocuni !

I have a mild preference for MIT, but leave the decision to @blueyed

**Comment by classner** [comment]
Hi guys!

Would be awesome if @kynan or @blueyed could make the call and add a license file - I would love to use the project but can't as long as there's no license... :)

**Comment by jayvdb** [comment]
ping @blueyed

**Comment by blueyed** [comment]
I'd prefer GPL, but am OK to go with whatever @antocuni / you pick(s) - seeing that GPL is not an option he likes.

**Comment by jayvdb** [comment]
Using GPL may be a bit problematic given pdbpp is BSD, if they cant be uncoupled.
It would however allow tighter coupling with readline.

**Comment by kynan** [comment]
Any remaining objections to license this as MIT, @blueyed ?

**Comment by kynan** [comment]
Can we get this resolved? This is [blocking](https://github.com/conda-forge/fancycompleter-feedstock/pull/9) `conda` packaging. @blueyed

**Comment by classner** [comment]
:) Any updates on this, @blueyed ? This would unblock...

**Comment by kynan** [comment]
@blueyed friendly ping, this is still blocking: conda-forge/fancycompleter-feedstock#11 currently

**Comment by kynan** [comment]
Friendly ping, @blueyed

**Comment by blueyed** [comment]
@antocuni 

> I am fine to add a LICENSE file to repo and release my work under either BSD or MIT. I leave the final decision to the current maintainers also because there are commits which are not mine and for which I don't have any right to decide which license to apply.

As for me I am fine with whatever OSS license you chose.

Please commit it to this repo, so @kynan and other packagers/people are happy.

**Comment by blueyed** [comment]
> Any remaining objections to license this as MIT, @blueyed ?

No.  (having this as a starred email in my notifications folder)

**Comment by kynan** [comment]
@antocuni would you be happy to commit a LICENSE file to this repository, as requested by @blueyed ?

**Comment by antocuni** [comment]
I already said two years ago that I was fine with adding a license. Anyway, I opened #38 to fix this

**Comment by kynan** [comment]
Thank you, much appreciated.
